### ISSUE TITLE
时间选择有bug

### ISSUE THREAD

**Issue by qsfty** [sahooz/oh-date-picker#3]
第466行有bug

错误：
      case DateTimeFormat.Hm:
        fmtStr = 'HH:ss'
        break

正确：
case DateTimeFormat.Hm:
        fmtStr = 'HH:mm'
        break

**Comment by sahooz** [comment]
确实有问题，手误

**Comment by sahooz** [comment]
已修复，OpenHarmony三方库中心仓审核中
